services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    volumes:
      - ./config/:/opt/keycloak/data/import:ro
      - ./storage/keycloakdb.mv.db:/opt/keycloak/data/h2/keycloakdb.mv.db
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --import-realm'
